# Generated by Django 2.2.10 on 2020-02-19 10:02

import concrete_datastore.concrete.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concrete', '0002_auto_20200218_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordchangetoken',
            name='expiry_date',
            field=models.DateTimeField(default=concrete_datastore.concrete.models.compute_pwd_change_token_expiry),
        ),
    ]
