# Generated by Django 2.2.12 on 2020-05-26 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concrete', '0004_itempack'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concretepermission',
            options={'verbose_name': 'Permission'},
        ),
        migrations.AlterModelOptions(
            name='concreterole',
            options={'verbose_name': 'Role'},
        ),
    ]
