# Generated by Django 2.2.15 on 2021-01-13 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('concrete', '0005_auto_20200526_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicModelManagerRetrieve',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('public', models.BooleanField(default=True)),
                ('name', models.CharField(default='', max_length=255)),
                ('additional_filtering', models.BooleanField(default=False)),
                ('can_admin_groups', models.ManyToManyField(blank=True, related_name='group_administrable_publicmodelmanagerretrieves', to='concrete.Group')),
                ('can_admin_users', models.ManyToManyField(blank=True, related_name='administrable_publicmodelmanagerretrieves', to=settings.AUTH_USER_MODEL)),
                ('can_view_groups', models.ManyToManyField(blank=True, related_name='group_viewable_publicmodelmanagerretrieves', to='concrete.Group')),
                ('can_view_users', models.ManyToManyField(blank=True, related_name='viewable_publicmodelmanagerretrieves', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_publicmodelmanagerretrieves', to=settings.AUTH_USER_MODEL)),
                ('defaultdivider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='divider_publicmodelmanagerretrieves', to='concrete.DefaultDivider')),
            ],
            options={
                'verbose_name': 'PublicModelManagerRetrieve',
                'verbose_name_plural': 'PublicModelManagerRetrieves',
                'ordering': ('-modification_date', '-creation_date'),
            },
        ),
    ]
