# Generated by Django 2.2.18 on 2021-02-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concrete', '0006_publicmodelmanagerretrieve'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='ipv4'),
        ),
    ]
