# Generated by Django 2.2.18 on 2021-02-17 14:53

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concrete', '0007_project_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='gps_address',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
