# Generated by Django 2.2.24 on 2021-09-15 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('concrete', '0009_auto_20210304_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletedmodel',
            name='model_name',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='AnonymousModel',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('public', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('can_admin_groups', models.ManyToManyField(blank=True, related_name='group_administrable_anonymousmodels', to='concrete.Group')),
                ('can_admin_users', models.ManyToManyField(blank=True, related_name='administrable_anonymousmodels', to=settings.AUTH_USER_MODEL)),
                ('can_view_groups', models.ManyToManyField(blank=True, related_name='group_viewable_anonymousmodels', to='concrete.Group')),
                ('can_view_users', models.ManyToManyField(blank=True, related_name='viewable_anonymousmodels', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_anonymousmodels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AnonymousModel',
                'verbose_name_plural': 'AnonymousModels',
                'ordering': ('-modification_date', '-creation_date'),
            },
        ),
    ]
