# Generated by Django 3.2.13 on 2022-06-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concrete', '0010_auto_20210915_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsonfield',
            name='json_field',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
