# Generated by Django 3.2.16 on 2022-11-15 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concrete', '0011_alter_jsonfield_json_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaildevice',
            name='digits',
            field=models.PositiveSmallIntegerField(choices=[(6, 6), (8, 8)], default=6, help_text='The number of digits to expect in a token.'),
        ),
        migrations.AddField(
            model_name='emaildevice',
            name='drift',
            field=models.SmallIntegerField(default=0, help_text='The number of time steps the prover is known to deviate from our clock.'),
        ),
        migrations.AddField(
            model_name='emaildevice',
            name='last_t',
            field=models.BigIntegerField(default=-1, help_text='The t value of the latest verified token. The next token must be at a higher time step.'),
        ),
        migrations.AddField(
            model_name='emaildevice',
            name='mfa_mode',
            field=models.CharField(choices=[('MFA_OTP', 'Otp'), ('MFA_EMAIL', 'Email')], default='MFA_EMAIL', max_length=250),
        ),
        migrations.AddField(
            model_name='emaildevice',
            name='step',
            field=models.PositiveSmallIntegerField(default=30, help_text='The time step in seconds.'),
        ),
        migrations.AddField(
            model_name='emaildevice',
            name='t0',
            field=models.BigIntegerField(default=0, help_text='The Unix time at which to begin counting steps.'),
        ),
        migrations.AddField(
            model_name='emaildevice',
            name='throttling_failure_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of successive failed attempts.'),
        ),
        migrations.AddField(
            model_name='emaildevice',
            name='throttling_failure_timestamp',
            field=models.DateTimeField(blank=True, default=None, help_text='A timestamp of the last failed verification attempt. Null if last attempt succeeded.', null=True),
        ),
    ]
