# Generated by Django 3.2.19 on 2023-06-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concrete', '0012_auto_20221115_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='storage_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
