# Generated by Django 3.2.16 on 2023-02-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concrete', '0013_instancepermission_systemversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemversion',
            name='version',
            field=models.CharField(default='0.1.0', max_length=255),
        ),
    ]
