# Generated by Django 3.2.20 on 2023-08-02 15:17

import concrete_datastore.concrete.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concrete', '0013_project_storage_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='secureconnectcode',
            name='expiry_date',
            field=models.DateTimeField(default=concrete_datastore.concrete.models.compute_auth_secure_connect_code_expiry),
        ),
        migrations.AddField(
            model_name='secureconnecttoken',
            name='expiry_date',
            field=models.DateTimeField(default=concrete_datastore.concrete.models.compute_auth_secure_connect_expiry),
        ),
    ]
